import Link from "next/link";

const STAGES = [
  {
    step: "01",
    title: "Single-image body estimation",
    tech: "PyMAF-X",
    body: "A single front-facing photo is passed to PyMAF-X, a regression network that fits the SMPL-X parametric body model to 2D image evidence via iterative feature alignment. The output is a 10-dimensional β (shape) vector encoding height, weight distribution, and proportions — independent of pose.",
  },
  {
    step: "02",
    title: "SMPL-X body model",
    tech: "SMPL-X β params",
    body: "The β vector is decoded through the SMPL-X linear blend skinning model to produce a posed mesh of 10,475 vertices across 55 joints (22 body + 30 MANO hand + jaw/eyes). A T-pose is generated by zeroing the pose parameters and keeping only the shape — the canonical form used for measurement and export.",
  },
  {
    step: "03",
    title: "Measurement extraction",
    tech: "Plane-slice + joint chain",
    body: "Six body measurements are extracted directly from the T-pose mesh geometry. Waist and hip are computed via horizontal plane slices through the mesh at the relevant joint heights, fitting an ellipse to the cross-section perimeter. Shoulder width uses vertex-based acromion estimation. Inseam and arm length are measured via joint-chain traversal.",
  },
  {
    step: "04",
    title: "Scale calibration",
    tech: "Height-proportional scaling",
    body: "The SMPL-X metric scale is ambiguous from a single image. The user-supplied height in cm is used to compute a global scale factor from the model's predicted height (heel-to-crown joint chain), which is then applied uniformly to vertices and joint positions before measurement extraction.",
  },
  {
    step: "05",
    title: "Skinned GLB export",
    tech: "Raw GLTF binary",
    body: "The scaled mesh is exported as a binary GLB with VRM-compatible humanoid bone names, top-4 LBS weights per vertex, 100 SMPL-X expression morph targets (via a pre-computed 52×100 ARKit→expression-PCA matrix), and eye/jaw auxiliary bones. The GLB is generated without pygltflib — raw GLTF binary written directly, keeping the backend dependency footprint minimal.",
  },
  {
    step: "06",
    title: "Real-time pose driving",
    tech: "MediaPipe PoseLandmarker",
    body: "In the browser, MediaPipe PoseLandmarker (WASM, client-side, no server round-trip) streams 33 world-space landmarks at ~30 fps. Each frame, joint directions are derived from landmark pairs and decomposed into local bone rotations via swing decomposition — setFromUnitVectors(restDir, observedDir) projected into parent-local space. One Euro Filter smooths landmarks; quaternion SLERP smooths bone output.",
  },
  {
    step: "07",
    title: "Hand and face driving",
    tech: "MediaPipe HandLandmarker + FaceLandmarker",
    body: "21 hand landmarks per hand drive 15 finger bones each via per-bone swing decomposition, with REST directions derived lazily from the GLB bind pose at runtime (WeakMap cache, auto-invalidated on GLB reload). Face blendshapes (52 ARKit scores) are mapped to 100 SMPL-X expression params via matrix multiply, with a 30-frame neutral calibration at webcam start to zero the resting expression.",
  },
  {
    step: "08",
    title: "Forearm pronation redistribution",
    tech: "Swing-twist decomposition",
    body: "SMPL-X uses a single forearm bone, causing mesh collapse under pronation/supination if the full twist is applied at the wrist. The wrist quaternion is swing-twist decomposed around the forearm local X-axis; 50% of the twist is bled to the LowerArm bone each frame, with the hand bone pre-compensated by the inverse twist to preserve world-space wrist orientation.",
  },
];

export default function MethodPage() {
  return (
    <div className="flex flex-col min-h-full bg-[#fafaf8] text-[#0c0c0a]">
      {/* Topbar — same as studio */}
      <header className="flex items-center justify-between px-6 h-14 border-b border-black/[0.07] bg-white shrink-0">
        <div className="flex items-center gap-2.5">
          <div
            className="w-[22px] h-[22px] rounded-[7px]"
            style={{
              background: "linear-gradient(135deg, #d9a98d 0%, #b07a5e 100%)",
              boxShadow: "inset 0 1px 0 rgba(255,255,255,0.4)",
            }}
          />
          <span className="font-semibold text-sm tracking-tight">digital-twin</span>
          <span className="text-black/50 text-sm">· studio</span>
        </div>
        <nav className="flex gap-1">
          <Link href="/" className="px-3.5 py-1.5 text-xs font-medium rounded-md text-black/50 hover:text-black/80 transition-colors">
            Studio
          </Link>
          <Link href="/method" className="px-3.5 py-1.5 text-xs font-medium rounded-md bg-[#f0eee9] text-[#0c0c0a]">
            Method
          </Link>
          <a
            href="https://github.com/Kaustubh-1420/digital-twin"
            target="_blank"
            rel="noopener noreferrer"
            className="px-3.5 py-1.5 text-xs font-medium rounded-md text-black/50 hover:text-black/80 transition-colors"
          >
            GitHub ↗
          </a>
        </nav>
        <div className="w-24" />
      </header>

      {/* Content */}
      <div className="flex-1 max-w-2xl mx-auto px-6 py-16 w-full">
        <div className="mb-12">
          <h1 className="font-serif font-normal text-[36px] leading-[1.1] tracking-tight mb-3">
            How it works.
          </h1>
          <p className="text-sm text-black/55 leading-relaxed max-w-lg">
            Eight stages from a single photo to a real-time personalized avatar in the browser. Every layer is custom-built — no off-the-shelf avatar SDK.
          </p>
        </div>

        <div className="flex flex-col">
          {STAGES.map((s, i) => (
            <div key={s.step} className={`flex gap-6 py-8 ${i < STAGES.length - 1 ? "border-b border-black/[0.06]" : ""}`}>
              <div className="shrink-0 w-6 pt-0.5">
                <span className="font-mono text-[11px] text-black/30 tracking-wider">{s.step}</span>
              </div>
              <div className="flex flex-col gap-1.5">
                <div className="flex items-baseline gap-2.5 flex-wrap">
                  <h2 className="text-[15px] font-medium tracking-tight">{s.title}</h2>
                  <span className="font-mono text-[11px] text-black/40 border border-black/10 rounded-full px-2 py-0.5">{s.tech}</span>
                </div>
                <p className="text-[13px] text-black/60 leading-relaxed">{s.body}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-black/[0.06] flex items-center justify-between">
          <p className="text-[12px] text-black/40">
            Backend on HF Spaces ZeroGPU · Frontend on Vercel · All inference client-side or serverless
          </p>
          <Link href="/" className="text-[12px] text-black/50 hover:text-black/80 transition-colors">
            ← Back to studio
          </Link>
        </div>
      </div>
    </div>
  );
}
